Product.create(title: 'Raiders of the Lost Ark DVD', price: rand(100), available: [true, false].sample)
Product.create(title: 'Star Wars 1 DVD', price: rand(100), available: [true, false].sample)
Product.create(title: 'Star Wars 2 DVD', price: rand(100), available: [true, false].sample)
Product.create(title: 'Star Wars 3 DVD', price: rand(100), available: [true, false].sample)
Product.create(title: 'Star Wars 4 DVD', price: rand(100), available: [true, false].sample)
Product.create(title: 'Star Wars 5 DVD', price: rand(100), available: [true, false].sample)
Product.create(title: 'Star Wars 6 DVD', price: rand(100), available: [true, false].sample)
Product.create(title: 'Star Wars 7 DVD', price: rand(100), available: [true, false].sample)
